[workspace]

[package]
name = "test-log-support"
version = "0.1.0"
publish = false
edition = "2018"

[dependencies]
tracing = { path = "..", features = ["log", "log-always"] }
log = { version = "0.4", features = ["std"] }
