language: rust
sudo: false
rust:
# This represents the minimum Rust version supported by tracing. Updating this
# should be done in a dedicated PR and cannot be greater than two 0.x
# releases prior to the current stable.
- 1.34.0
- stable
- beta
- nightly

script:
- cargo test --verbose --all

jobs:
  include:
  - script: cargo test --all --all-features
    name: "all features"
    rust: stable
  - script: cargo fmt --all -- --check
    install: rustup component add rustfmt-preview
    name: "rustfmt"
    rust: stable
