language: rust
sudo: false
rust:
# This represents the minimum Rust version supported by tracing. Updating this
# should be done in a dedicated PR and cannot be greater than two 0.x
# releases prior to the current stable.
- 1.34.0
- stable
- beta
- nightly

script:
- cargo test --all

jobs:
  include:
  - script:
    - (cd tracing/test-log-support && cargo test)
    - (cd tracing/test_static_max_level_features && cargo test)
    name: "feature flags"
    rust: stable
  - script: cargo fmt --all -- --check
    install: rustup component add rustfmt-preview
    name: "rustfmt"
    rust: stable
  - script: cargo test --features=doctest-readme --all
    name: "doctest readme"
    rust: nightly

