language: rust
sudo: false
rust:
# This represents the minimum Rust version supported by Tokio. Updating this
# should be done in a dedicated PR and cannot be greater than two 0.x
# releases prior to the current stable.
- 1.26.0
- stable
- beta
- nightly

script:
- cargo test --verbose -p tokio-trace
- cargo test --verbose -p tokio-trace-futures
- cargo test --verbose -p tokio-trace-subscriber
- cargo test --verbose -p tokio-trace-tower
- cargo test --verbose -p tokio-trace-tower-http
- cargo test --verbose -p tokio-trace-log
- cargo test --verbose -p tokio-trace-env-logger

jobs:
  include:
  # The proc macros crate does _not_ build on Rust 1.26.0, so it is tested
  # in a separate stage.
  - stage: test
    name: "test proc-macros"
    script:
    - cargo test -p tokio-trace-macros
    rust: stable
  - script: cargo fmt --all -- --check
    install: rustup component add rustfmt-preview
    name: "rustfmt"
    rust: stable
