[build]
  command = """
    rustup install nightly --profile minimal \
      && cargo doc --no-deps --all-features
    """
  publish = "target/doc"

[build.environment]
  RUSTDOCFLAGS="""
    -D warnings \
    --force-warn rustdoc::redundant-explicit-links \
    --force-warn renamed-and-removed-lints \
    --cfg docsrs
    """

[[redirects]]
  from = "/"
  to = "/tracing"
