[build]
  command = """
    rustup install nightly --profile minimal \
      && cargo doc --no-deps
    """
  publish = "target/doc"

[build.environment]
  RUSTDOCFLAGS="""
    --cfg docsrs \
    --html-before-content /opt/build/repo/assets/warning.html \
    --html-in-header /opt/build/repo/noindex.html \
    --extend-css /opt/build/repo/assets/warning.css \
    """

[[redirects]]
  from = "/"
  to = "/tracing"
