[package]
name = "tracing-tower"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
Compatibility with the `tower` ecosystem.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing"]
license = "MIT"

[features]
default = ["tower-layer", "tower-make", "http"]
tower-make = [
    "tower_make",
    "pin-project",
]

[dependencies]
tracing = { path = "../tracing", version = "0.1"}
tracing-futures = { version = "0.2.1", path = "../tracing-futures", features = ["std-future"] }
futures = "0.3"
tower-service = "0.3"
tower-layer = { version = "0.3", optional = true }
tower_make = { package = "tower-make", version = "0.3", optional = true }
pin-project = { version = "0.4", optional = true }
http = { version = "0.1", optional = true }

[badges]
azure-devops = { project = "tracing/tracing", pipeline = "tokio-rs.tracing", build = "1" }
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
