[package]
name = "tracing-tower"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
Compatibility with the `tower` ecosystem.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing"]
license = "MIT"
rust-version = "1.63.0"

[features]
default = ["tower-layer", "tower-make"]
tower-make = [
    "tower_make",
    "pin-project-lite",
]

[dependencies]
tracing = { path = "../tracing", version = "0.2", default-features = false, features = ["std"] }
tracing-futures = { version = "0.3", path = "../tracing-futures", features = ["std-future"] }
futures = "0.3.21"
tower-service = "0.3.2"
tower-layer = { version = "0.3.1", optional = true }
tower_make = { package = "tower-make", version = "0.3.0", optional = true }
pin-project-lite = { version = "0.2.9", optional = true }
http = { version = "0.2.8", optional = true }

[badges]
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
