[package]
name = "tracing-serde"
version = "0.1.0"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
edition = "2018"

[dependencies]
serde = "1"
tracing-core = { version = "0.1", path = "../tracing-core" }

[dev-dependencies]
serde_json = "1.0"
tracing = { version = "0.1", path = "../tracing" }
