[package]
name = "tracing-macros"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[dependencies]
tracing = { version = "0.1", path = "../tracing" }

[dev-dependencies]
tracing-log = { path = "../tracing-log" }
env_logger = "0.5"

[badges]
azure-devops = { project = "tracing/tracing", pipeline = "tokio-rs.tracing", build = "1" }
maintenance = { status = "experimental" }
