[package]
name = "tracing-log"
version = "0.1.1"
authors = ["Tokio Contributors <team@tokio.rs>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
Provides compatibility between `tracing` and the `log` crate.
"""
categories = [
    "development-tools::debugging",
    "asynchronous",
]
keywords = ["logging", "tracing", "log"]
license = "MIT"
readme = "README.md"

[features]
default = ["log-tracer", "trace-logger", "std"]
log-tracer = []
trace-logger = []
std = ["log/std"]

[dependencies]
tracing-core = "0.1.2"
log = { version = "0.4", features = ["std"] }
lazy_static = "1.3.0"
env_logger = { version = "0.6", optional = true }

[dev-dependencies]
tracing = "0.1"

[badges]
azure-devops = { project = "tracing/tracing", pipeline = "tokio-rs.tracing", build = "1" }
maintenance = { status = "actively-maintained" }
