[package]
name = "tracing-log"
version = "0.1.3"
authors = ["Tokio Contributors <team@tokio.rs>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
Provides compatibility between `tracing` and the `log` crate.
"""
categories = [
    "development-tools::debugging",
    "asynchronous",
]
keywords = ["logging", "tracing", "log"]
license = "MIT"
readme = "README.md"
rust-version = "1.49.0"

[features]
default = ["log-tracer", "trace-logger", "std"]
std = ["log/std", "tracing-core/std"]
log-tracer = []
trace-logger = []
interest-cache = ["lru", "ahash", "lazy_static"]

[dependencies]
tracing-core = { path = "../tracing-core", version = "0.1.17", default-features = false }
log = { version = "0.4", default-features = false }
lazy_static = { version = "1.3.0", optional = true }
env_logger = { version = "0.7", optional = true }
lru = { version = "0.7.0", optional = true }
ahash = { version = "0.7.4", optional = true }

[dev-dependencies]
tracing = { path = "../tracing", version = "0.1"}
tracing-subscriber = { path = "../tracing-subscriber" }
criterion = { version = "0.3", default_features = false }

[badges]
maintenance = { status = "actively-maintained" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "logging"
harness = false
