[package]
name = "tracing-log"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[dependencies]
tracing-core = "0.1"
tracing-subscriber = { path = "../tracing-subscriber" }
log = "0.4"
lazy_static = "1.3.0"
