[package]
name = "tracing-log"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[dependencies]
tracing-core = "0.1.2"
tracing-subscriber = { path = "../tracing-subscriber" }
log = { version = "0.4", features = ["std"] }
lazy_static = "1.3.0"

[dev-dependencies]
tracing = "0.1"

[badges]
azure-devops = { project = "tracing/tracing", pipeline = "tokio-rs.tracing", build = "1" }
maintenance = { status = "experimental" }
