[package]
name = "tracing"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag
version = "0.1.6"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tracing/0.1.6/tracing"
description = """
Application-level tracing for Rust.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
    "no-std",
]
keywords = ["logging", "tracing", "metrics", "async"]
edition = "2018"

[dependencies]
tracing-core = { version = "0.1.5", default-features = false }
log = { version = "0.4", optional = true }
tracing-attributes = "0.1.2"
cfg-if = "0.1.9"

[dev-dependencies]
ansi_term = "0.11"
humantime = "1.2"
futures = "0.1"
log = "0.4"
criterion = { version = "0.2", default_features = false }

[features]
default = ["std"]

max_level_off   = []
max_level_error = []
max_level_warn  = []
max_level_info  = []
max_level_debug = []
max_level_trace = []

release_max_level_off   = []
release_max_level_error = []
release_max_level_warn  = []
release_max_level_info  = []
release_max_level_debug = []
release_max_level_trace = []

# This feature flag is no longer necessary.
async-await = []

std = ["tracing-core/std"]

[[bench]]
name = "subscriber"
harness = false

[[bench]]
name = "no_subscriber"
harness = false

[badges]
azure-devops = { project = "tracing/tracing", pipeline = "tokio-rs.tracing", build = "1" }
maintenance = { status = "actively-developed" }

[target.'cfg(not(feature = "std"))'.dependencies]
spin = "0.5"
