[package]
name = "tracing"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag
version = "0.1.1"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tracing/0.1.1/tracing"
description = """
A scoped, structured logging and diagnostics system.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing"]
edition = "2018"

[dependencies]
tracing-core = "0.1.1"
log = { version = "0.4", optional = true }
cfg-if = "0.1.9"

[dev-dependencies]
ansi_term = "0.11"
humantime = "1.2"
futures = "0.1"
log = "0.4"
criterion = { version = "0.2", default_features = false }
# These are used for the "basic" example from the tracing-prototype repo,
# which is currently not included as it used the `tracing-log` crate, and
# that crate is currently unstable.
# env_logger = "0.5"
# tracing-log = { path = "../tracing-log" }

[features]
max_level_off   = []
max_level_error = []
max_level_warn  = []
max_level_info  = []
max_level_debug = []
max_level_trace = []

release_max_level_off   = []
release_max_level_error = []
release_max_level_warn  = []
release_max_level_info  = []
release_max_level_debug = []
release_max_level_trace = []

doctest-readme = []

[[bench]]
name = "subscriber"
harness = false

[[bench]]
name = "no_subscriber"
harness = false

[badges]
travis-ci = { repository = "tokio-rs/tracing", branch = "master" }
maintenance = { status = "actively-developed" }
